model:
#  pretrained_name: "cointegrated/rubert-tiny"
  pretrained_name: "sergeyzh/rubert-tiny-turbo"
  labels: ["errorClient", "operation", "other", "document", "sms", "vtbo", "cashback", "transfer"]
  save_to: models/best_8c_turbo

training:
  learning_rate: 2e-5
  batch_size: 64
  num_epochs: 20
  weight_decay: 0.01
  save_total_limit: 5
  output_path: results_8c
  logs: logs
  metric_for_best_model: fbeta

data:
  path: "data/df_8c_aug.csv"
  text_column: "text"
  label_column: "label"
  split_column: "split" 
  val_split: 0.2
  max_text_length: 512

logging:
  uri: "http://localhost:5000"
  experiment_name: "bert-text-classification-aug-8c-turbo"
